version: '3.8'
services:
  gateway-services:
    build: ./
    container_name: gateway-services
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env
  