version: '3.8'
services:
  auth-services:
    build: ./
    container_name: auth-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env
    depends_on:
      - authPostgresDB
    command: sh -c "npx prisma migrate deploy && npm start"


  authPostgresDB:
    image: postgres:latest
    container_name: authPostgresDB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: authDB
    ports:
      - "5434:5432"
    volumes:
      - ./auth_db_data:/var/lib/postgresql/data
    
volumes:
  auth_db_data:
     